FROM python:3.11

WORKDIR /app

COPY requirements.txt /app

RUN pip install --no-cache-dir -r requirements.txt

COPY server /app/server
COPY common /app/common

EXPOSE 9024/udp

CMD ["python", "/app/server/server.py"]